### ISSUE TITLE
Remove support in blackbox tests for building rpms

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/ci#410]
If there is useful infrastructure for running the actual blackbox tests we should keep it.

We can remove for sure:
* blackbox/stratisd.spec
* blackbox/stratis-cli.spec
* blackbox/build-and-package.sh

I don't know about the others.

**Comment by bgurney-rh** [comment]
The package builds could be performed by a system running the scripts in the `mockbuild_test` directory (which also has the up-to-date stratisd.spec and stratis-cli.spec files).  I'm anticipating that stratis-blackbox-run.sh would check to see if the stratisd and stratis-cli packages are installed (instead of installing and un-installing them itself).

The parse_json.py script should stay; it is used for parsing the test config file.

Since the packages are going to be built before the stratis-blackbox-run.sh script, the reset-upstream-stratis-repos.sh script will probably be able to be removed.
