### ISSUE TITLE
Consider putting cleanup script in this repo as well

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/ci#8]
This is the script that is run if the test is aborted.

We previously decided it didn't really make sense to put here, but now I'm not so sure it woudn't be useful.

**Comment by mulkieran** [comment]
This is still a judgement call, so deferring until August.

**Comment by bgurney-rh** [comment]
I posted #18: "ci: add teardown script for stratisd test", for review.

It turns out that the thinpool-pool device in the stratisd.sh test "engine::strat_engine::pool::tests::real_test_add_datadevs" undergoes a suspend/resume cycle about once every few seconds during that test, leaving a low probability of that device being suspended, and being unable to be removed, since I/O is pending.

After a lot of testing today, via terminating the runalltests.sh test during the above test, I feel confident that this script is more resilient than the old one.

**Comment by mulkieran** [comment]
@bgurney-rh are we able to close this issue?

**Comment by bgurney-rh** [comment]
Yes; I'll close it now.  The teardown.sh script successfully addresses the issue.
